controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'arn:aws:acm:us-east-2:533267033180:certificate/654c1cbd-998c-49fb-ba61-5114b42499f8'
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'http'
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 'https'
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    enabled: true
  extraArgs:
    enable-ssl-passthrough: ''
  ingressClass: 'nginx'
  publishService:
    enabled: true
