on:
  push:
    branches:
      - main

name: Infrastructure tofu apply

defaults:
  run:
    working-directory: './k8s/infra'
env:
  access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  region: us-east-2

permissions:
  pull-requests: write

jobs:
  tofu-plan:
    runs-on: ubuntu-latest
    name: Tofu Apply
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: OpenTofu Validate
        id: validate
        run: tofu validate -no-color

      - name: OpenTofu Plan
        id: plan
        run: tofu plan -no-color
        continue-on-error: true

      - name: OpenTofu Apply
        id: apply
        run: tofu apply --auto-approve -no-color
        continue-on-error: true
